# WEEK 1 - DAY 3
## NUMPY FUNDAMENTALS

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
print(arr)
print(arr.dtype)
print(arr.shape)

[1 2 3 4]
int64
(4,)


In [5]:
#2D ARRAY
m1=np.array([[1,2,3,4],[5,6,7,8]])
print(m1)
print(m1.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [9]:
print(arr[0])
print(arr[-1])
print(m1[0,2])
print(m1[:,1])

1
4
3
[2 6]


In [12]:
arr1=np.array([10,20,30,40])
print(arr+arr1)
print(arr*2)
print(arr1/10)

[11 22 33 44]
[2 4 6 8]
[1. 2. 3. 4.]


In [16]:
#NUMPY FUNCTIONS
print(np.mean(arr))
print(np.min(m1))
print(np.max(arr1))
print(np.sum(arr))
print(np.std(arr))

2.5
1
40
10
1.118033988749895


In [24]:
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.arange(0,20,2))
print(np.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [25]:
print(np.random.seed(0))
print(np.random.randint(1,100,size=5))
print(np.random.randn(3,3))

None
[45 48 65 68 68]
[[ 0.37025538  1.04053075 -1.51698273]
 [-0.86627621 -0.05503512 -0.10731045]
 [ 1.36546718 -0.09769572 -2.42595457]]
